version: '3.4'

volumes:
  mysite.db.volume:
    name: mysite.db.volume
  gunicorn-run:
    name: gunicorn-run


services:
  h2o:
    build: ./h2o
    container_name: mysite.h2o
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "./etc/letsencrypt:/etc/letsencrypt"
      - ./static:/static
      - gunicorn-run:/var/sock/gunicorn
    depends_on:
      - webapi
    environment:
      - EMAIL
      - AGREEMENT=yes

  db:
    image: mariadb:10.3
    container_name: mysite.db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysitepass
      TZ: 'Asia/Tokyo'
    volumes:
      - mysite.db.volume:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  webapi:
    build: ./webapi
    container_name: mysite.webapi
    command: gunicorn config.wsgi:application --bind=unix:/var/sock/gunicorn/django.sock
    volumes:
      - ./src:/code
      - ./static:/static
      - gunicorn-run:/var/sock/gunicorn
    ports:
      - "8000:8000"
    depends_on:
      - db